# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 05:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0002_accesstoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='marvel',
            new_name='xmen',
        ),
    ]
